import { PrismaClient } from "@prisma/client"
import bcrypt from "bcrypt"
import generator from "generate-password"
// local imports
import * as config from "../src/config"

const prisma = new PrismaClient()

async function main() {
    await prisma.permission.createMany({
        data: [
            {
                id: 1,
                name: "user_read_all",
                description: null,
                displayName: "Read all",
                group: "User",
                isActive: true,
            },
            {
                id: 2,
                name: "user_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "User",
                isActive: true,
            },
            {
                id: 3,
                name: "user_create",
                description: null,
                displayName: "Create",
                group: "User",
                isActive: true,
            },
            {
                id: 4,
                name: "user_update",
                description: null,
                displayName: "Update",
                group: "User",
                isActive: true,
            },
            {
                id: 5,
                name: "user_self_read",
                description: "Fetch single record",
                displayName: "Self read",
                group: "User",
                isActive: true,
            },
            {
                id: 6,
                name: "user_reset_password",
                description: null,
                displayName: "Reset password",
                group: "User",
                isActive: true,
            },
            {
                id: 7,
                name: "user_self_update",
                description: null,
                displayName: "Self update",
                group: "User",
                isActive: true,
            },
            {
                id: 8,
                name: "user_self_change_password",
                description: null,
                displayName: "Self change password",
                group: "User",
                isActive: true,
            },
            {
                id: 9,
                name: "user_login",
                description: null,
                displayName: "User - Login",
                group: "Public",
                isActive: true,
            },
            {
                id: 10,
                name: "role_read_all",
                description: null,
                displayName: "Read all",
                group: "Role",
                isActive: true,
            },
            {
                id: 11,
                name: "role_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Role",
                isActive: true,
            },
            {
                id: 12,
                name: "role_create",
                description: null,
                displayName: "Create",
                group: "Role",
                isActive: true,
            },
            {
                id: 13,
                name: "role_update",
                description: null,
                displayName: "Update",
                group: "Role",
                isActive: true,
            },
            {
                id: 14,
                name: "permission_read_all",
                description: null,
                displayName: "Read all",
                group: "Permission",
                isActive: true,
            },
            {
                id: 15,
                name: "permission_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Permission",
                isActive: true,
            },
            {
                id: 16,
                name: "subscription_read_all",
                description: null,
                displayName: "Read all",
                group: "Subscription",
                isActive: true,
            },
            {
                id: 17,
                name: "subscription_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Subscription",
                isActive: true,
            },
            {
                id: 18,
                name: "subscription_create",
                description: null,
                displayName: "Create",
                group: "Subscription",
                isActive: true,
            },
            {
                id: 19,
                name: "subscription_update",
                description: null,
                displayName: "Update",
                group: "Subscription",
                isActive: true,
            },
            {
                id: 20,
                name: "industry_read_all",
                description: null,
                displayName: "Read all",
                group: "Industry",
                isActive: true,
            },
            {
                id: 21,
                name: "industry_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Industry",
                isActive: true,
            },
            {
                id: 22,
                name: "industry_create",
                description: null,
                displayName: "Create",
                group: "Industry",
                isActive: true,
            },
            {
                id: 23,
                name: "industry_update",
                description: null,
                displayName: "Update",
                group: "Industry",
                isActive: true,
            },
            {
                id: 24,
                name: "skill_read_all",
                description: null,
                displayName: "Read all",
                group: "Skill",
                isActive: true,
            },
            {
                id: 25,
                name: "skill_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Skill",
                isActive: true,
            },
            {
                id: 26,
                name: "skill_create",
                description: null,
                displayName: "Create",
                group: "Skill",
                isActive: true,
            },
            {
                id: 27,
                name: "skill_update",
                description: null,
                displayName: "Update",
                group: "Skill",
                isActive: true,
            },
            {
                id: 28,
                name: "company_read_all",
                description: null,
                displayName: "Read all",
                group: "Company",
                isActive: true,
            },
            {
                id: 29,
                name: "company_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Company",
                isActive: true,
            },
            {
                id: 30,
                name: "company_create",
                description: null,
                displayName: "Create",
                group: "Company",
                isActive: true,
            },
            {
                id: 31,
                name: "company_update",
                description: null,
                displayName: "Update",
                group: "Company",
                isActive: true,
            },
            {
                id: 32,
                name: "customer_read_all",
                description: null,
                displayName: "Read all",
                group: "Customer",
                isActive: true,
            },
            {
                id: 33,
                name: "customer_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Customer",
                isActive: true,
            },
            {
                id: 34,
                name: "customer_update",
                description: null,
                displayName: "Update",
                group: "Customer",
                isActive: true,
            },
            {
                id: 35,
                name: "customer_reset_password",
                description: null,
                displayName: "Reset password",
                group: "Customer",
                isActive: true,
            },
            {
                id: 36,
                name: "customer_subscription_read_all",
                description: null,
                displayName: "Read all",
                group: "Customer - Subscription",
                isActive: true,
            },
            {
                id: 37,
                name: "customer_subscription_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Customer - Subscription",
                isActive: true,
            },
            {
                id: 38,
                name: "customer_subscription_create",
                description: null,
                displayName: "Create",
                group: "Customer - Subscription",
                isActive: true,
            },
            {
                id: 39,
                name: "customer_subscription_update",
                description: null,
                displayName: "Update",
                group: "Customer - Subscription",
                isActive: true,
            },
            {
                id: 40,
                name: "candidate_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Candidate",
                isActive: true,
            },
            {
                id: 41,
                name: "candidate_create",
                description: null,
                displayName: "Create",
                group: "Candidate",
                isActive: true,
            },
            {
                id: 42,
                name: "candidate_update",
                description: null,
                displayName: "Update",
                group: "Candidate",
                isActive: true,
            },
            {
                id: 43,
                name: "candidate_work_history_read_all",
                description: null,
                displayName: "Read all",
                group: "Candidate - Work history",
                isActive: true,
            },
            {
                id: 44,
                name: "candidate_work_history_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Candidate - Work history",
                isActive: true,
            },
            {
                id: 45,
                name: "candidate_work_history_create",
                description: null,
                displayName: "Create",
                group: "Candidate - Work history",
                isActive: true,
            },
            {
                id: 46,
                name: "candidate_work_history_update",
                description: null,
                displayName: "Update",
                group: "Candidate - Work history",
                isActive: true,
            },
            {
                id: 47,
                name: "candidate_certification_read_all",
                description: null,
                displayName: "Read all",
                group: "Candidate - Certification",
                isActive: true,
            },
            {
                id: 48,
                name: "candidate_certification_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Candidate - Certification",
                isActive: true,
            },
            {
                id: 49,
                name: "candidate_certification_create",
                description: null,
                displayName: "Create",
                group: "Candidate - Certification",
                isActive: true,
            },
            {
                id: 50,
                name: "candidate_certification_update",
                description: null,
                displayName: "Update",
                group: "Candidate - Certification",
                isActive: true,
            },
            {
                id: 51,
                name: "candidate_read_all",
                description: null,
                displayName: "Read all",
                group: "Candidate - Basic",
                isActive: true,
            },
            {
                id: 52,
                name: "candidate_basic_bulk_create",
                description: null,
                displayName: "Bulk create",
                group: "Candidate - Basic",
                isActive: true,
            },
            {
                id: 53,
                name: "candidate_basic_upload_profile_image",
                description: null,
                displayName: "Upload profile image",
                group: "Candidate - Basic",
                isActive: true,
            },
            {
                id: 54,
                name: "agent_read_all",
                description: null,
                displayName: "Read all",
                group: "Agent",
                isActive: true,
            },
            {
                id: 55,
                name: "agent_read",
                description: "Fetch single record",
                displayName: "Read",
                group: "Agent",
                isActive: true,
            },
            {
                id: 56,
                name: "agent_create",
                description: null,
                displayName: "Create",
                group: "Agent",
                isActive: true,
            },
            {
                id: 57,
                name: "agent_update",
                description: null,
                displayName: "Update",
                group: "Agent",
                isActive: true,
            },
        ],
    })

    await prisma.role.createMany({
        data: [
            {
                id: 1,
                name: "System Administrator",
                description: "Super user role generated by the system",
                isSystemGenerated: true,
                isActive: true,
            },
            {
                id: 2,
                name: "User",
                description: "Normal user role generated by the system",
                isSystemGenerated: true,
                isActive: true,
            },
            {
                id: 3,
                name: "Agent",
                description: "Agent role generated by the system",
                isSystemGenerated: true,
                isActive: true,
            },
        ],
    })

    await prisma.user.create({
        data: {
            id: 1,
            fullName: config.SysAdm.name,
            isActive: true,
        },
    })

    const generatedPassword = generator.generate({
        length: 20,
        lowercase: true,
        uppercase: true,
        numbers: true,
        strict: true,
        symbols: true,
    })
    console.log(`Please keep password safe: ` + generatedPassword)

    await prisma.userLogin.create({
        data: {
            id: 1,
            userId: 1,
            roleId: 1,
            email: config.SysAdm.email,
            isSystemGenerated: true,
            passwordHash: bcrypt.hashSync(generatedPassword, 12),
        },
    })
    const l = 57
    const arrPerms = []
    for (let i = 1; i <= l; i++) {
        arrPerms.push({
            id: i,
            roleId: 1,
            permissionId: i,
        })
    }

    await prisma.rolePermission.createMany({
        data: [
            ...arrPerms,
            {
                id: l + 1,
                roleId: 2,
                permissionId: 9,
            },
        ],
    })
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
