export default {
    none: 0,
    user_read_all: 1,
    user_read: 2,
    user_create: 3,
    user_update: 4,
    user_self_read: 5,
    user_reset_password: 6,
    user_self_update: 7,
    user_self_change_password: 8,
    user_login: 9,
    role_read_all: 10,
    role_read: 11,
    role_create: 12,
    role_update: 13,
    permission_read_all: 14,
    permission_read: 15,
    subscription_read_all: 16,
    subscription_read: 17,
    subscription_create: 18,
    subscription_update: 19,
    industry_read_all: 20,
    industry_read: 21,
    industry_create: 22,
    industry_update: 23,
    skill_read_all: 24,
    skill_read: 25,
    skill_create: 26,
    skill_update: 27,
    company_read_all: 28,
    company_read: 29,
    company_create: 30,
    company_update: 31,
    customer_read_all: 32,
    customer_read: 33,
    customer_update: 34,
    customer_reset_password: 35,
    customer_subscription_read_all: 36,
    customer_subscription_read: 37,
    customer_subscription_create: 38,
    customer_subscription_update: 39,
    candidate_read: 40,
    candidate_create: 41,
    candidate_update: 42,
    candidate_work_history_read_all: 43,
    candidate_work_history_read: 44,
    candidate_work_history_create: 45,
    candidate_work_history_update: 46,
    candidate_certification_read_all: 47,
    candidate_certification_read: 48,
    candidate_certification_create: 49,
    candidate_certification_update: 50,
    candidate_read_all: 51,
    candidate_basic_bulk_create: 52,
    candidate_basic_upload_profile_image: 53,
    agent_read_all: 54,
    agent_read: 55,
    agent_create: 56,
    agent_update: 57,
    agent_self_read: 58,
    agent_self_update: 59,
    agent_self_change_password: 60,
    candidate_upload_batch_self_read_all: 61,
    candidate_upload_batch_read_all: 62,
    admin_candidate_verification_read_all: 63,
    admin_candidate_verification_read: 64,
    candidate_verification_read_all: 65,
    candidate_verification_read: 66,
    candidate_verification_create: 67,
    candidate_verification_update: 68,
    category_read_all: 69,
    category_read: 70,
    category_create: 71,
    category_update: 72,
    admin_candidate_upload_batch_change_pricing_template: 73,
    admin_candidate_upload_batch_create: 74,
    candidate_upload_batch_create: 75,
    batch_priority_read_all: 76,
    batch_priority_read: 77,
    batch_priority_create: 78,
    agent_pricing_template_read_all: 79,
    agent_pricing_template_read: 80,
    agent_pricing_template_create: 81,
    agent_pricing_template_set_active: 82,
    admin_other_industry_category_read_all: 83,
    admin_other_industry_category_update: 84,
    admin_candidate_upload_batch_approval: 85,
    admin_user_activity_read_all:93,
    admin_user_activity_read:94,
    admin_user_login_activity_read:95,
    admin_user_login_activity_read_all:96,
    user_login_activity_read:97,
    user_activity_read:98,

}
